### ISSUE TITLE
Data points on top of the home page don't scale properly on smaller screens

### ISSUE THREAD

**Issue by dbhume** [BCDevExchange/BCDevExchange-app#140]
There is too much screen real estate used by the data points menu on smaller screens. Have tested on a Surface Pro 3 and an IPad Air. Looks good on mobile devices, however. @dyona has seen what I'm talking about. 

Please test against multiple device resolutions.

**Comment by kelpisland** [comment]
Fred - there are some issues with the home page resolution on iPad. Let's take a look, hopefully we can fix today.

**Comment by f-w** [comment]
Should be fixed.
