### ISSUE TITLE
Allow editors to hide/show different sections in the profile page.

### ISSUE THREAD

**Issue by dy2288** [BCDevExchange/BCDevExchange-app#150]
As an author of a profile page I would like to determine which content is displayed on the web (not UAT) so that I can work on draft content.

DOD
1. Create a wire frame.
2. Conduct a reasonable amount of usability testing.
3. Create a working prototype

Created by: Paul/Loren

Approach

Connect with:
Fred, Todd, Loren, Rommel

**Comment by f-w** [comment]
This is part of #151.
