### ISSUE TITLE
Connecting gitter feed to the profile page

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/BCDevExchange-app#152]
As a developer I would like to see who is discussing what regarding the content of the repo so that I know who to engage with should I be interested in working with this feature.

Created by Paul/Loren

DOD

Approach

Who to connect with

**Comment by paulroberts68** [comment]
A balsamiq wire frame exists for this

**Comment by f-w** [comment]
@paulroberts68 -  you don't want this to be in Bull's Eye Center?

**Comment by f-w** [comment]
I don't have access to balsamiq and below is the wire frame I have. I cannot see where does gitter feed goes to. 

![image](https://cloud.githubusercontent.com/assets/12823994/10554958/348cbe9e-741d-11e5-99e4-a19412d684b6.png)

**Comment by pcrossley** [comment]
Down at the very bottom, where it says "Engage with Us"

**Comment by f-w** [comment]
Each profile page is only associated with 1 github repo which is where "Go to GitHub" button goes to. Why there are multiple gitter feeds?

**Comment by f-w** [comment]
Now available in UAT, for example check out https://uat.bcdevexchange.org/programs/City%20of%20Kamloops. It supports multiple gitter lists despite only 1 is displayed for now.
