### ISSUE TITLE
Project browser opt-out

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/BCDevExchange-app#153]
Turn on the opt-out function in project team member browsers to prevent metrics contamination.

**Comment by dy2288** [comment]
The options for browser opt-out are unfortuantely both not very elegant:

1. Users can opt-out of Google Analytics entirely by installing a Google extension ("Google Analytics Opt-out Add-on" for Chrome or an equivilant opt-out extension for FireFox, no official one exists).

2. We can't exclude traffic by IP in Google Analytics itself, however we can do so in our BCDevX code, by not loading the GA script for certain IPs. This is a "hacky" way of doing it and exposes our internal IPs to the public via Github. 

Given these options, I think the preferred course of action is to accept that our traffic will be affected to some extent by our internal usage, unless there are other suggestions on the table. @kelpisland agrees. FYI @pcrossley.

**Comment by SupaMic** [comment]
Actually you can exclude IP's in Google Analytics by setting up a view filter and just be sure to set that as the default view.  
https://support.google.com/analytics/answer/1034840?hl=en

I've had to do this similarly to filter out Referral Spam which warps analytic's quite a bit for lower traffic sites.

**Comment by dy2288** [comment]
Hi SupaMic, thanks! I thought that by anonymizing IPs we wouldn't have access to that but it seems like the option does exist uner Filters. Appreciate the assistance!
