### ISSUE TITLE
As a program owner I would like to use the DevEx CI stack so that I can validate code changes via the lab.

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/BCDevExchange-app#158]
Part of the lab value prop is to speed up the deployment of new code so that program owners can collaborate efficiently with developers. This will become particularly useful for accepting code when using the pay for pull process. 

Created by Fred/Peter

DOD 
1. Demonstrate how a program owner would use the service

**Comment by f-w** [comment]
Proposed solution:
Prerequisites, requirements and assumptions:
1. One vm with docker installed.
2. Jenkins
3. Program owner has to reserve lab namespace in advance. Each namespace allows one web app
4. Program owner has to pack their web app into docker (i.e. creating a Dockerfile). This requirement has some further implications:
  *  The web app has to be runnable in Linux, which may rule out some type of apps.
  *  Program owner is responsible to apply code change to docker. For simplicity it's preferable to create Dockerfile in the same web application to avoid extra downloads.
5. The app and Dockerfile has to be in a public GitHub repository
6. Dockerfile is allowed to expose multiple ports but only one port can be made externally accessible

The workflow works like this:
1. Program owner register their Git repo containing the Docker file to DevX
2. DevX programmatically create a project on Jenkins and setup web hooks
3. First time and every time a commit is made in GitHub, Jenkins build and docker image, delete previous running container and start a new one. 
4. Program owner are notified failed build result and has certain degree of control of the Jenkins Project.
5. Program owner can access the web app via https://<lab_namespace>.bcdevexchange.org anytime.

**Comment by f-w** [comment]
@watkinspd @kelpisland , see my proposal for lab implementation above.
Question: what is the value proposition of the lab comparing to some other public DevOps application hosting offerings such as Heroku which has a free tier?

**Comment by kelpisland** [comment]
@f-w I think the main value prop in that case is the "namespace" for public sector developers. It offers the clear expectation that this work is not production but still approved for public collaboration. What we get (dev exchange) is a more consistent experience across projects and offer a helping hand to getting things off the ground quickly.

**Comment by pcrossley** [comment]
What's the sense of the size of this?

**Comment by f-w** [comment]
Size/capacity is a concern because:
1. People tend to "set it and forget it" when the service is free
2. There is a limit how many lab instances a VM can handle above which performance degrade rapidly. The limit is unknown and depends on the application launched.

Given that, it's probably necessary not only to limit who can create instances but how many instances an authorized person is allowed to create. I'm thinking 3-5 is probably a good number.

**Comment by paulroberts68** [comment]
I'm closing this issue as the work has been superseded by openshift
