### ISSUE TITLE
Profile page for EnvReportingBC

### ISSUE THREAD

**Issue by lmullane** [BCDevExchange/BCDevExchange-app#164]
As Environmental Reporting BC,  I need a profile page in the BCDevExchange.

Created by: Loren

DOD
1. Profile page in production

Approach

Connect with EnvReportingBC

**Comment by lmullane** [comment]
@dy2288 Can you please create me a profile page with all the features for Environmental Reporting BC. Thanks in advance.

**Comment by dy2288** [comment]
Done: programs/Environmental%20Reporting%20BC

**Comment by lmullane** [comment]
Page is with program area for review: https://bcdevexchange.org/programs/Environmental%20Reporting%20BC
