### ISSUE TITLE
DriveBC webcam API specification

### ISSUE THREAD

**Issue by lmullane** [BCDevExchange/BCDevExchange-app#165]
As DriveBC, I want to do an open spec development for a Webcam API.

DOD:
Technical process for API specification.
Launch of engagement

**Comment by lmullane** [comment]
@f-w @pcrossley

**Comment by DavidR8** [comment]
Kickoff meeting Oct 22 with Tran2

**Comment by DavidR8** [comment]
Replaced by #76
