### ISSUE TITLE
Approve profile page for EnvReportingBC

### ISSUE THREAD

**Issue by lmullane** [BCDevExchange/BCDevExchange-app#169]
As Environmental Reporting BC,  I need a profile page in the BCDevExchange.

Created by: Loren

DOD
1. Profile page approved and in PROD.

Approach
With EnvReportingBC for approval

**Comment by lmullane** [comment]
@dy2288 This page is approved by the program owner: https://bcdevexchange.org/programs/Environmental%20Reporting%20BC

Please add here using the first sentence from the Description on the profile: https://bcdevexchange.org/programs

@watkinspd

**Comment by dy2288** [comment]
Done.

**Comment by lmullane** [comment]
Thanks!

On Nov 10, 2015 12:18 PM, dy2288 <notifications@github.com> wrote:

Done.

-
