### ISSUE TITLE
Modify lab banner

### ISSUE THREAD

**Issue by AlexWhiteIncorporated** [BCDevExchange/BCDevExchange-app#17]
Change Discovery to new language - Exploration

Yellow still makes sense as a colour, so not sure about changing it to match the new badge scheme

**Comment by GregTurner** [comment]
fixed BCDevEchange
fixed WSO2

**Comment by GregTurner** [comment]
Over to devin for CKAN

**Comment by h3devin** [comment]
Lab banner modified to match new style on CKAN sandbox.
