### ISSUE TITLE
As as developer, I want to find issues on a profile page so I can decide what to work on.

### ISSUE THREAD

**Issue by lmullane** [BCDevExchange/BCDevExchange-app#170]
Use GitHub API to display a list of issues on a profile page in Work with Us section. Include labels for skills, $1000, help wanted.

Approach:

Use GitHub API to display issues with labelled information on profile page.

DOD
Issues (hyperlinked) and labels including skills displayed in Work with Us section on Profile Page.

Connect with Rommel, Loren

**Comment by sheaphillips** [comment]
Adding this to Sprint 16 as it is closely related to the "global issue list"
