### ISSUE TITLE
As a interested developer, I want to understand the mechanics the Pay for Pull process works so I can participate.

### ISSUE THREAD

**Issue by lmullane** [BCDevExchange/BCDevExchange-app#171]
Create list of information that developers will need to know to participate in the Pay for Pull process (e.g. Include links to GitHub help).

DOD
Content approved and posted on new webpage. 
Link to page on all profile pages.

Connect with Loren, Rommel

**Comment by pcrossley** [comment]
fork a repo with the intention of getting is "participation for pay for pull"
all the information we need as a developer
Is the developer already committed to participate?
is this a list of questions or the content?
eg
1)setup a paypal business account...
2) setup a github account
3) how to fork a repo

**Comment by sheaphillips** [comment]
Refine in "white board to code" session.

**Comment by kelpisland** [comment]
We have added a repo specifically for rapid adoption content. The wiki is now updated with the pay for pull instructions.
