### ISSUE TITLE
Parts of Speech vocabulary

### ISSUE THREAD

**Issue by cstua** [BCDevExchange/BCDevExchange-app#176]
Parts of Speech vocabulary should be re-imported as a hierarchical vocabulary (as the current one is)

BASIC:
Verb, Noun, Pronoun, Adjective, Adverb, Preposition, Conjunction, Interjection, Particle

ADVANCED:
All others

**Comment by f-w** [comment]
I think it belongs to FV, not BCDevExchange-app
