### ISSUE TITLE
As a technical contact, I want to understand how I need to collaborate with developers working on a Pay for Pull opportunity

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/BCDevExchange-app#181]
The UX research has established that technical contacts for client programs did not understand how (or when) to engage with developers regarding pay for pull opportunities.

Created by the UX research team

DOD
1. Description of solution av, content etc
2. Design suggestions (wireframes)

Connect with Loren/Rommel.

**Comment by sheaphillips** [comment]
largely Technical Contact persona's how to guide (similar to 171 for developers)
