### ISSUE TITLE
As a technical contact, I need guidance so I can understand open source and open source licensing.

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/BCDevExchange-app#184]
During the UX research it was established that technical contacts within the client programs were unclear how to create an open source project and select the correct licensing. 

Created by the UX research team

DOD
1. Content suggestions
2. Design suggestions (wireframes)

Connect with Loren/Rommel

**Comment by DavidR8** [comment]
Note that we have a document which details open source licensing in the BC Govt context.

**Comment by lmullane** [comment]
@DavidR8 Super. Could you please flip it to me when you have a moment.
