### ISSUE TITLE
As a technical contact, I want guidance so I can choose whether I need a submission period for a Pay for Pull opportunity.

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/BCDevExchange-app#185]
During the UX research it was established that the technical contacts within the client programs did not understand if they needed to create a fixed submission period during which bids or work would be collected; in accordance with current procurement practices and policy. 

Created by the UX team

DOD
1. Content that informs the user of correct procedure.
2. Design changes (wireframes)

Connect with Loren/Rommel

**Comment by DavidR8** [comment]
I suggest that the program owner will also want this guidance.
