### ISSUE TITLE
As a developer, I want to know how to contact the program so I can get my questions about a Pay for Pull opportunity answered.

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/BCDevExchange-app#186]
Research indicated that it was not intuitively obvious how (or when) to contact contact program about Pay for Pull opportunity.

Created by the UX research team

DOD
1. Content and design suggestion (wireframe).
2. Design validated with users. 

Connect with Loren or Rommel.

**Comment by sheaphillips** [comment]
Refine in "white board to code" session.

**Comment by sheaphillips** [comment]
Could be "section" in 171 (how to guide)

**Comment by kelpisland** [comment]
Need an issue template that details how to contact people. Setting up gitter office hours for chat.

**Comment by kelpisland** [comment]
We added the concept of technical contact to the pay4pull instructions and clearly described the contact process through github comments.
Closes #186
