### ISSUE TITLE
As a developer, I want a high level diagram so I can quickly understand how pay for pull works.

### ISSUE THREAD

**Issue by lmullane** [BCDevExchange/BCDevExchange-app#191]
As a developer, I want a high level diagram so I can understand how pay for pull works.

DOD:
Diagram on profile pages and global list page that shows the developer workflow.

**Comment by sheaphillips** [comment]
Refine in "white board to code" session.

**Comment by sheaphillips** [comment]
Could be part of 171?

**Comment by kelpisland** [comment]
The info graphics added to the work list page are good enough for mvp
