### ISSUE TITLE
As a program owner and developer, I need more context so I can understand what profiles and labs mean.

### ISSUE THREAD

**Issue by lmullane** [BCDevExchange/BCDevExchange-app#195]
As a program owner and developer, I need more context so I can understand what profiles and labs mean.

DOD: Replace navigation options with featured sections below the fold that provide context and call to actions (e.g. Labs, Early Adopters).

**Comment by kelpisland** [comment]
This will be tackled as part of the homepage re-design (whiteboard to code)
