### ISSUE TITLE
As a program owner, I want the number of closed pull requests displayed on my profile page so I can see how active my project is.

### ISSUE THREAD

**Issue by lmullane** [BCDevExchange/BCDevExchange-app#198]
As a program owner, I want the number of closed pull requests displayed on my profile page so I can see how active my project is.

Approach
The stats counter on the profile pages currently pulls open pull requests from the GitHub API. It should display the closed pull requests.

**Comment by lmullane** [comment]
@f-w @ll911 Let me know if you have questions.

**Comment by lmullane** [comment]
@paulroberts68 @kelpisland Just added another story to the sprint. Please advise if you would prefer this to stay out.

**Comment by kelpisland** [comment]
I think it's a good idea, have you talked to @f-w to see if he can fit it in?
