### ISSUE TITLE
As a user I need to accept the exchange terms when I sign up for the exchange so that I can use the services.

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/BCDevExchange-app#202]
The user needs to accept the terms and conditions for the exchange when they sign up. 

Created by Paul

DOD
1. Users must click on and accept the terms.

Connect with Peter and David H.

**Comment by leslieanderson** [comment]
Does "user" refer to a BPS entity?

**Comment by DavidR8** [comment]
In the abstract I would say yes. That said the story should perhaps say "As a public sector entity..."
Thoughts?

David

On Dec 4, 2015, at 7:46 AM, leslieanderson <notifications@github.com<mailto:notifications@github.com>> wrote:


Does "user" refer to a BPS entity?

-
