### ISSUE TITLE
Create Courtenay Profile Page

### ISSUE THREAD

**Issue by karsmith** [BCDevExchange/BCDevExchange-app#211]
As a program owner for City of Courtenay I need to create a profile page so that I can access the DevEx services.

Created by Peter

DOD
2. Draft complete
3. Submitted for review to City of Courtenay Executive

Connect with 
Loren, Peter, David W.

**Comment by MeaghanRStewart** [comment]
City of Courtenay is unable to meet until after the new year. Profile page will not be created or published until after this date.

**Comment by MeaghanRStewart** [comment]
Courtenay has advised that they do not want a profile page. Awaiting next steps from David Hume.
