### ISSUE TITLE
Publish Courtenay Profile Page

### ISSUE THREAD

**Issue by karsmith** [BCDevExchange/BCDevExchange-app#212]
DOD: All approvals for launch of Courtenay Profile Page have been obtained and page launched.

**Comment by MeaghanRStewart** [comment]
City of Courtenay is unable to meet until after the new year. Profile page will not be created or published until after this date.

**Comment by MeaghanRStewart** [comment]
Courtenay has advised that they do not want a profile page. Awaiting next steps from David Hume.
