### ISSUE TITLE
Create Environmental Assessment Office (EAO) Profile Page

### ISSUE THREAD

**Issue by karsmith** [BCDevExchange/BCDevExchange-app#213]
As a program owner for the Environmental Assessment Office I need to create a profile page so that I can access the DevEx services.
DOD
2. Draft complete
3. Submitted for review to Environmental Assessment Office Executive

Connect with 
Loren, Peter, David W.

**Comment by lmullane** [comment]
@dy2288 Can you please create a new profile page for the Environment Assessment Office and link to this repo: https://github.com/bcgov/esm-server 

Please hide skills and the Work With Us section.

Thanks!

**Comment by dy2288** [comment]
@lmullane, created DB entry. If you could add it to the YAML file that would be great. URL would be /programs/Environment%20Assessment%20Office

**Comment by lmullane** [comment]
@dy2288 Could you hide the skills, work with us, and news sections please?

**Comment by lmullane** [comment]
@f-w Could you please hide Community and the News on this page: https://bcdevexchange.org/programs/Environment%20Assessment%20Office

**Comment by f-w** [comment]
@lmullane, done
