### ISSUE TITLE
Publish EAO Profile Page

### ISSUE THREAD

**Issue by karsmith** [BCDevExchange/BCDevExchange-app#214]
DOD: All approvals for launch of EAO Profile Page have been obtained and page launched.

**Comment by MeaghanRStewart** [comment]
EAO profile page is not in the current sprint.  Moving to product backlog.

**Comment by lmullane** [comment]
Readme file needs to be updated before profile page goes live. This will not happen until after the sprint, so moving this story back to the backlog.
