### ISSUE TITLE
As a public sector dev user I need to know that Microsoft has become a DevEx lab partnership and I need to know what services are being provided

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/BCDevExchange-app#215]
The Microsoft partnership needs to be advertised/communicated so that the public sector devs come to the exchange, sign-up and explore the opportunities. 

Created by Peter

DOD
1. Comms plan

Connect with Peter

**Comment by DavidR8** [comment]
Assigned to @kelpisland

**Comment by kelpisland** [comment]
@watkinspd  - can you connect me with the folks at MS and I'll get this rolling
