### ISSUE TITLE
As a site visitor I want to easily navigate to content focused on my persona.

### ISSUE THREAD

**Issue by sheaphillips** [BCDevExchange/BCDevExchange-app#216]

**Comment by sheaphillips** [comment]
Need to review front page design and navigation so it support role-based navigation.

**Comment by sheaphillips** [comment]
As a point of reference, they've done a nice job here: https://www.gov.uk/service-manual

**Comment by sheaphillips** [comment]
A mid-fidelity mockup of the home page redesign is: 
<img width="1262" alt="screenshot 2015-12-09 11 10 00" src="https://cloud.githubusercontent.com/assets/698658/11695828/1284893a-9e66-11e5-9486-a34b6af3de09.png">

**Comment by sheaphillips** [comment]
@kelpisland: for the current sprint, I intend to adapt the home page within the existing app to use this layout, vs. re-homing portions of the app in GitHub pages, since this would be a little disruptive and hasn't been fully walked through from a process/workflow implication perspective.

**Comment by kelpisland** [comment]
OK - sounds good to me. As part of our retrospective let's bring the GH Pages approach to the table for discussion with the larger group.

**Comment by sheaphillips** [comment]
@kelpisland - also, see #217 for some elaboration on "aligning content change workflows", which is connected to the GitHub pages thing a bit - i.e. some changes could be made through Github pages, but even there, there would be different categories requiring different skills. Also, we want to make sure that UAT preview, PR workflow etc. are understood/accounted for in whatever we come up with.

**Comment by kelpisland** [comment]
Agreed - we don't want to solve a problem by just creating a different problem.

**Comment by sheaphillips** [comment]
Here is the latest incarnation - the elements in the mid-fidelity mockup, now incorporated into the app.

At the moment, I've removed the additional banner elements, pending discussion around content.

<img width="1268" alt="screenshot 2015-12-09 14 12 58" src="https://cloud.githubusercontent.com/assets/698658/11700536/3a626620-9e7f-11e5-93a7-a28253094877.png">

@kelpisland, @paulroberts68, @lmullane  : thoughts?

**Comment by lmullane** [comment]
Looks good, @sheaphillips. Let's find a time to discuss refining content. @ragbay what do you think?

**Comment by ragbay** [comment]
Overall, I feel this is a lot more simple to understand and navigate for a user. 

Minor styling around the size on layout of the work with us button, and possibly adding a little more content just above that given how much space we've saved with this layout.

Curious if there were conversations about the "fat footer" concept that we sketched out, and if that was still in scope?

Thanks,
Rommel

**Comment by lmullane** [comment]
Thanks, @ragbay. There are other elements below the fold that are not showing here. I believe those include a fat footer, albeit a slimmer version than what I presented in the wireframe. @sheaphillips, is that correct?

**Comment by sheaphillips** [comment]
Fat footer can be in scope, but we will need to figure out the content for
it - the fat footer in my earlier mockups just had sample content.

I've removed the other "below the fold" elements for the moment as the
content/intent was unclear to me.  They can be added back in if we figure
those items out.
ᐧ

**Comment by kelpisland** [comment]
I like the layout - especially the "work with us" banner button.

@lmullane :  Not sure about the "win an award" phrase - is that final copy?

**Comment by DavidR8** [comment]
@kelpisland … @lmullane and I were just discussing the copy… short answer is ‘no, not final copy’ ☺

**Comment by lmullane** [comment]
@kelpisland @DavidR8 yes, we still need to wordsmith. Work With Us wasn't a big winner with the devs. What about 'Code With Us'?

**Comment by sheaphillips** [comment]
+1 for Code With Us
ᐧ

**Comment by kelpisland** [comment]
:+1: code with us

**Comment by paulroberts68** [comment]
+1 for Code With Us

-1 for win an award
