### ISSUE TITLE
Page unresponsive

### ISSUE THREAD

**Issue by AlexWhiteIncorporated** [BCDevExchange/BCDevExchange-app#23]
After the steps in #22

Navigate to Sign Up
Activate Sign Up button
System displays Accounts page
Press the browser back button
Press Sign Up button again 

Pressing the Link your GitHub account button results in 504 Gateway Time-Out (nginx/1.4.6 (Ubuntu)

**Comment by GregTurner** [comment]
unable to recreate
likely a small outaged of NodeJS
