### ISSUE TITLE
Add standard footer bar elements to the BC DevExchange site

### ISSUE THREAD

**Issue by DavidR8** [BCDevExchange/BCDevExchange-app#232]
As a site visitor I need to see the Disclaimer, Privacy Accessibility and Copyright notices so that I understand my rights rights and obligations and those of government

**Comment by sheaphillips** [comment]
@DavidR8: Do we have content and layout for these? 

@lmullane :  do @f-w or I need to look at this?

**Comment by lmullane** [comment]
@DavidR8 will confirm the correct content. @sheaphillips

**Comment by DavidR8** [comment]
@sheaphillips Sure do...
Disclaimer: http://www2.gov.bc.ca/gov/admin/disclaimer.page
Privacy: http://www2.gov.bc.ca/gov/content/home/privacy
Accessibility: http://www2.gov.bc.ca/gov/admin/accessibility.page
Copyright: http://www2.gov.bc.ca/gov/admin/copyright.page

**Comment by lmullane** [comment]
@f-w Could you please add the above standard disclaimers to page footer.

**Comment by lmullane** [comment]
@f-w @DavidR8 The correct Disclaimer is already on the website: https://www.bcdevexchange.org/disclaimer 

So we just need to take the text from these pages and have it appear on BCDevExchange pages: 
Privacy: http://www2.gov.bc.ca/gov/content/home/privacy 
Accessibility: http://www2.gov.bc.ca/gov/admin/accessibility.page
Copyright: http://www2.gov.bc.ca/gov/admin/copyright.page

**Comment by DavidR8** [comment]
The copyright one will be mod’ed. Am waiting for feedback from Legal.
