### ISSUE TITLE
Use API client libraries in place of lower level code for API integrations.

### ISSUE THREAD

**Issue by sheaphillips** [BCDevExchange/BCDevExchange-app#233]
We are currently using "raw"/request based integrations for accessing GitHub and presumably other APIs. It would be preferable to use API providers' client libraries to reduce low-level code, and simplify implementation.  GitHub would be the obvious place to start.  There are several candidates listed here: https://developer.github.com/libraries/
# payforpullcandidate.

**Comment by kelpisland** [comment]
@BK01 will be fleshing this issue out as a possible candidate for P4P
