### ISSUE TITLE
User can quickly see that the program offers an API resource when they visit a profile page

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/BCDevExchange-app#235]
As a developer I need to know that the profile page (program) I am visiting offers an API service so that I am aware that there are digital resources available as well as pay-for-pull opportunities.

Created by: David

Connect with: Rommel, Mark, Loren.

**Comment by mark-a-wilson** [comment]
The first icon on Profile pages is now titled "APIs & Resources" - that should help. 

Next, on the Government Partners page (https://bcdevexchange.org/programs), we could look at:
a) a filter function, to allow you to see only partners that have an open API 
b) an "Open API" label or icon that could be stuck to each Partner's description (enable you to see, at a glance, that that partner has an open API), and/or
c) a link on this page to the full API list (http://api.bcdevexchange.org)
