### ISSUE TITLE
As an entrepreneur and developer, I want an explanation of what a partner is on the partners' list page so I can understand the value of the partners' pages to me.

### ISSUE THREAD

**Issue by lmullane** [BCDevExchange/BCDevExchange-app#238]
As an entrepreneur and developer, I want an explanation of what a partner is on the partners' list page so I can understand the value of the partners' pages to me.

DOD:
1. Replace "Profiles" with "Partners" as the list title
2. Mirror design of "Code with us" page in PDF mockup
3. Include image
4. Overlay big heading on image: "Government Partners"
5. Overlay smaller tagline on image under heading: "Meet government innovators open to new ways to develop technology."
6. Include contextual content under image: "Discover government innovators from British Columbia experimenting with technology development. Explore APIs and code you can use, and find opportunities to work together."
7. Remove tags in list (i.e. Collaboration, Participation, etc.)
8. Have default list appear in alphabetical order

**Comment by f-w** [comment]
@lmullane, for 7, instead of changing code, you can remove tags in yml file.

**Comment by lmullane** [comment]
@f-w I will do that.
