### ISSUE TITLE
As a returning DevX site user, I want to quickly navigate to functionality/sections within the site without scrolling down on the home page.

### ISSUE THREAD

**Issue by sheaphillips** [BCDevExchange/BCDevExchange-app#239]
It has been suggested that we provide a "hamburger" navigation element that provides direct links to features/sections within the page.

**Comment by lmullane** [comment]
@sheaphillips @ragbay Simple start would be to include these nav items: About, Partners, Code With Us, APIs, Blog, Sign Up, Login

Thoughts?
