### ISSUE TITLE
As a program lead I need development participants to sign-up to the exchange so that I can maintain a communication channel and build community.

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/BCDevExchange-app#259]
Created by Peter

DOD
Mechanism to encourage devs to sign-up to exchange and register for hackathon.

Connect with Peter

**Comment by f-w** [comment]
Can we ask wavefront capture user's GitHub account in registration for in order for BCDevX to recognize the participants?

**Comment by kelpisland** [comment]
I've opened a new issue so this one is now a duplicate: [BCDevExchange/Our-Project-Docs/#128](128)
