### ISSUE TITLE
As a community developer I want to see the list of completed pay of pul issues so I can get a quick idea of how much community work is getting completed.

### ISSUE THREAD

**Issue by kelpisland** [BCDevExchange/BCDevExchange-app#262]
As a community developer I want to see the list of completed pay of pul issues so I can get a quick idea of how much community work is getting completed.

DOD: A second list of completed Pay for Pull issues under the active list.
Possibly limit returned rows (by date/count)

**Comment by f-w** [comment]
cc @mark-a-wilson, @ragbay,
Questions:
1. Does this completed issue list appear under both /developers and in each profile page wherever applicable?
2. Is there any UI preference, or just duplicating the look-and-feel of existing active list?

**Comment by mark-a-wilson** [comment]
@f-w @ragbay In my mind, it would be valuable under both developers and in each profile page. And I think same look and feel.

**Comment by f-w** [comment]
Added list to both places in UAT.

**Comment by kelpisland** [comment]
Looks good - what do you guys think about stripping of the "help wanted" label from the closed tasks? @f-w - is the "closed date" available from the API call? if so that would be a good piece of information to display instead of the "help wanted" tag.
