### ISSUE TITLE
As the DevX business, I need to capture the story of our first completed P4P.

### ISSUE THREAD

**Issue by mark-a-wilson** [BCDevExchange/BCDevExchange-app#263]
Need to talk with all involved--the developer, DevX staff, Partner--to capture and document the experiences.

**Comment by mark-a-wilson** [comment]
Developer: Chad Oakenfold
Accepter of code: Steve Howard
People who worked on getting the Issue posted: ??

**Comment by lmullane** [comment]
@mark-a-wilson For the gov side, I would stick with Steve and Justin Hewitt.

**Comment by mark-a-wilson** [comment]
Meeting with Steve today and Justin tomorrow.

**Comment by mark-a-wilson** [comment]
Met with Steve and Justin and put their feedback into the experience map. Will try to connect with Chad Oakenfold in next couple days.

**Comment by mark-a-wilson** [comment]
Will connect with Evelyn to tag-team on future interviews.

**Comment by mark-a-wilson** [comment]
Completed interview with Chad Oakenfield this morning. Have captured story in two experience maps.
