### ISSUE TITLE
Differentiate between P4P and Community Contribution

### ISSUE THREAD

**Issue by ragbay** [BCDevExchange/BCDevExchange-app#269]
Revise "code with us" page content so that the community understands both p4p and "love" work/community collaboration is available.

DOD: 
- updated page content
- add the love/community work in the open/closed opportunities list if it exists.

**Comment by ragbay** [comment]
Will work with @mark-a-wilson to revise this content. Will then need technical implementation of the content changes.

**Comment by ragbay** [comment]
assigned to @lmullane and @paulroberts68 as per sprint 21 planning session.

**Comment by lmullane** [comment]
@paulroberts68  could you please send me the content. Cheers,
