### ISSUE TITLE
explore "sprint with us" option

### ISSUE THREAD

**Issue by ragbay** [BCDevExchange/BCDevExchange-app#279]
Explore the "spring with us" option by planning and confirming the possible approaches, and then planning how this might be tested.

DOD: 
1. document the approach for "sprint with us" activities
2. document a plan for testing the approach

**Comment by paulroberts68** [comment]
![img_2942](https://cloud.githubusercontent.com/assets/11237533/14825554/464be966-0b8f-11e6-8c6c-5446be698b85.jpg)

Amended journey map

**Comment by paulroberts68** [comment]
![img_0140](https://cloud.githubusercontent.com/assets/11237533/14825576/58384ec6-0b8f-11e6-90a9-f7a4eec9ddaf.JPG)

Initial thoughts

**Comment by paulroberts68** [comment]
![img_2993](https://cloud.githubusercontent.com/assets/11237533/14825640/927d5860-0b8f-11e6-8435-b68ca69dc897.jpg)

Options for discussion
