### ISSUE TITLE
Investigate options for timeboxing an issue

### ISSUE THREAD

**Issue by ragbay** [BCDevExchange/BCDevExchange-app#281]
DOD:
Document the timeboxing options generated from the P4P reservation ideation meeting (March 18)

**Comment by paulroberts68** [comment]
Spoke with Fred, Todd, Paul C, David W and Loren. The general opinion is that we continue to stick to the principle that the project should minimize the rule making and rely on the development community organization itself. Therefore, we are going to create some functionality that communicates to the development community that an issue is being worked on.
