### ISSUE TITLE
Roadmap widget

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/BCDevExchange-app#296]
As a product owner I want to be able to show the product roadmap on a web page so that users can see (and understand) what new features will be introduced over the next twelve months.

**Comment by sheaphillips** [comment]
I've made some edits to this around scrolling and fixed nav and header position.  I think it's closer to what was hoped for.  I can keep at it if this is on the right track. Next things would be to get the single long page scrolling and anchor based navigation.

**Comment by paulroberts68** [comment]
Great. Small bug, the favicon doesn't seem to show the BCGov logo
