### ISSUE TITLE
Simulate payment acceptance using alternative CC mechanism (other than PP)

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/BCDevExchange-app#297]
## Background
We have received feedback that developers would like the option to use their own credit card payment system instead of PayPay to receive payment for Pay for Pull opportunities.

### Story
As a product owner I need to understand what financial artifacts are provided by other credit card acceptance mechanisms (other than PayPal) so that we can determine if we can use these mechanisms as part of the P4P process in the near future. 

## Acceptance Criteria

1.  Follow the Contributing Guidelines and send us a Pull Request to this repository.
2. In the comments section of the Pull Request, include completed copy of the Pay for Pull Terms found in this repo that includes your name and email.
3. In the comments section of the Pull Request, include a link to an invoice for $5 generated by your credit card payment system that must be different than PayPal.
5. Upon receipt of payment generate a downloadable receipt of payment with your business information.

. 

## How to contribute

We will evaluate each pull request and choose the best solution to the issue based on the acceptance criteria. Submit the best solution and you could be paid $5 (THIS IS TEST).

Please read the (Contribution Guidelines)[https://github.com/BCDevExchange/BCDevExchange-app/blob/master/CONTRIBUTING.md] for the Terms that set the rules for participation in a Pay for Pull, including how you’ll get paid if you are successful.

Have questions? Please post your questions in the comments section below this issue.

And check out our (Partners page)[https://bcdevexchange.org/programs/BCDevExchange] for more information on our work.

**Comment by lmullane** [comment]
Hi all, I'm your contact for this issue. If you are interested in completing this work, please leave a comment here letting others know you are working on this.

**Comment by StormTide** [comment]
Sure, I'm game. Need the typical invoice detail, legal name, email, contact representative, address and whatever reference number you use for tracking payments and projects.

**Comment by lmullane** [comment]
Thanks for your interest, @StormTide. Yes, we would like the typical invoice detail.

**Comment by StormTide** [comment]
No, i mean, to send you an invoice, I need /your/ information ;)

**Comment by lmullane** [comment]
I see, but no that's not necessary. Here is an example of an (invoice)[https://www.paypal.com/ca/cgi-bin/webscr?cmd=_flow&SESSION=BzLlRdCDQhud-XCEz8WmUShGOKNlDRav24EyUMi9sdF6uAqNJa3n4nPs6RW&dispatch=50a222a57771920b6a3d7b606239e4d529b525e0b7e69bf0224adecfb0124e9b61f737ba21b0819848475f0da5465a2ea26eae033cbe3bda] we have paid via PayPal.

**Comment by StormTide** [comment]
That link doesn't work. My business uses Wave/Stripe for Invoicing... I can send via a link as required by the PR, but still need to know who I'm invoicing.

**Comment by lmullane** [comment]
Please invoice the Government of BC and put me down as the contact (Loren Mullane). To itemize the work completed use the title of this issue.

**Comment by StormTide** [comment]
legal name, email, contact representative, address. These are the fields I require to send an invoice ;)

Province of British Columbia? (Queen in right?...) 
Email (yours, the a/r depts, etc)
Address...

**Comment by lmullane** [comment]
For email Loren.Mullane@gov.bc.ca, Address 553 Superior Street, Victoria, BC, V8V 1T7, PO Box 9439, Stn Prov Govt, V8W 9V3

Province of British Columbia is the legal name.

**Comment by StormTide** [comment]
Hopefully that does the trick. I even fixed a couple quote marks for you ;)

**Comment by lmullane** [comment]
Thanks, @StormTide. Looks good.

**Comment by lmullane** [comment]
We have merged a PR for this issue.

**Comment by StormTide** [comment]
@lmullane payment received and receipt emailed to you. If you need the url as a PR or anything, let me know. Thanks for the $5 ;)

**Comment by lmullane** [comment]
Thanks for helping us test, @StormTide
