### ISSUE TITLE
Test P4P (In progress)

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/BCDevExchange-app#303]
Testing the new assignment U.I.

**Comment by paulroberts68** [comment]
@sheaphillips created the test P4P

**Comment by sheaphillips** [comment]
you can see it here : http://uat.bcdevexchange.org/developers

ᐧ

**Comment by mark-a-wilson** [comment]
Hey @sheaphillips  and @lmullane: 
Paul and I had a look at UAT just now and have some suggested revisions. Can we have a 30 minute “whiteboard-to-code” session at your earliest convenience this week?
