### ISSUE TITLE
How do I engage or request something from a public sector org?

### ISSUE THREAD

**Issue by GregTurner** [BCDevExchange/BCDevExchange-app#306]
As a developer working in the public sector, how do I engage with a public sector org to request something?  For example, I'd love to request from BC Gov to share their .www2.gov.bc.ca LESS/CSS stylesheets so I can write apps for BC Government without having to reverse engineer [www2.gov.bc.ca](www2.gov.bc.ca).  

Similar to:

[https://wet-boew.github.io/v4.0-ci/index-en.html](https://wet-boew.github.io/v4.0-ci/index-en.html)

**Comment by lmullane** [comment]
@GregTurner There is no central repository (i.e. skin) but we do have this Developers Guide to make it easier to build stuff. It has all the rules, colour codes, etc. Check it out and let us know if you have questions.

http://www2.gov.bc.ca/gov/content/about-gov-bc-ca/web-presence/developers-guide

**Comment by GregTurner** [comment]
Thanks @lmullane, more generally speaking, how would one request a resource be made available?

**Comment by lmullane** [comment]
Given the nature of your request I think what you did (opening an issue here) works best. In the future we may look at other channels, but GitHub issues can work for now. 

Any suggestions?

**Comment by GregTurner** [comment]
Could these github issues be surfaced on bcdevexchange.org?  It's nice to see a list of currently available API/code.  And even better for ones that people are requesting and means to do so.  It would help make visible the demand side to able to motivate government to make available resources.
