### ISSUE TITLE
Nginx & MongoDB config examples

### ISSUE THREAD

**Issue by markwooff** [BCDevExchange/BCDevExchange-app#309]
Hi BCDevExchange team,

I'm trying to stand up an instance of your web app and am running into an issue setting up Nginx and MongoDB as you had intended. The readme mentions that there are two sample files we can use: `/config/nginx` and `/config/local.conf`, but it looks like these have actually been included in your `.gitignore` file!

Do you think I could see some sample config files to get everything running smoothly? Thanks!

**Comment by ccoldwell** [comment]
Hey there mark,

Are you sure this is the app you are looking for? This is not our most current code, that lives in a project called 'devex'.  We are not currently running this code base anywhere to my knowledge.

Let me know.  I know I had this running before, but its been a while.

- Chris

**Comment by markwooff** [comment]
@ccoldwell that's great, thanks for pointing us in the right direction. Was almost able to get this one running but had to update a lot of npm packages. I can see the latest codebase at https://github.com/BCDevExchange/devex uses Docker so it should be pretty straightforward to set up. Thanks

**Comment by ccoldwell** [comment]
You're welcome, let me know if you have any trouble, just open a ticket over there.

that is an active codebase - working on it as we speak, so you may want to start with the master branch rather than the develop branch.
