### ISSUE TITLE
footer ? pop over on iOS 8.1 not hiding

### ISSUE THREAD

**Issue by GregTurner** [BCDevExchange/BCDevExchange-app#36]

**Comment by h3devin** [comment]
Looks like this is an issue with Bootstrap -- I attempted to use their dismissible popover inside the iOS Simulator and it demonstrated the same issue (it wouldn't dismiss).  They have another popover that dismisses when you click on the button a second time, this is probably our best bet as it also worked in the simulator.

**Comment by h3devin** [comment]
Fixed in discovery branch
