### ISSUE TITLE
"Learn how you can participate" doesn't navigate

### ISSUE THREAD

**Issue by GregTurner** [BCDevExchange/BCDevExchange-app#5]

**Comment by GregTurner** [comment]
Correction: after first click.

**Comment by h3devin** [comment]
This was likely to do with the Angular hash URLs.  Added a custom method to use anchor scrolling called `scrollTo`.  You can find an example inside the `HomeController`.  To use the method, just bind it to the `ng-click` event to whatever anchor tag that needs to scroll.

e.g.
```
<a href="" ng-click="scrollTo('a-div-to-scroll-to')">Time to scroll</a>
```
