### ISSUE TITLE
on account screen, save notification is nearly unnoticable

### ISSUE THREAD

**Issue by GregTurner** [BCDevExchange/BCDevExchange-app#60]
make it stand out more, and/or position it closer to button.  maybe a spinner on the button too?

**Comment by yilinglu** [comment]
Implemented interactive user message feature using ngFx (TweenMax + ngAnimate). 
See commit 0654d8543f19aab73dcbce1edf75ff0230de94f7

**Comment by GregTurner** [comment]
I have some feedback to discuss... I'll reopen

**Comment by GregTurner** [comment]
this is good for this iteration, some feedback for enhancements:

1. use relative positioning instead of absolute, position near button
2. use same font as the rest of the app
3. use a font-awesome X
