### ISSUE TITLE
Fetching... 

### ISSUE THREAD

**Issue by GregTurner** [BCDevExchange/BCDevExchange-app#64]
Sometimes the browser just sees "fetching".  As if the user is logged on, but the API calls are getting 401 which it appears the session on NodeJS is gone.  You can recreate this by deleting the connect.sid cookie while leaving the 'user' cookie behind.  

This session handling is a little too complex using two cookies to manage state.  I'm suggesting rewriting some of how the angularjs detects a logged on user.  E.g., avoid second cookie and just make one call to nodejs.  If you get a 401 turf the whole session and angularjs state too.

**Comment by GregTurner** [comment]
Maybe switch to tokens via OAuth2?  We need to do OAuth2 anyways for future integrations.

**Comment by yilinglu** [comment]
Fixed as part of the login-list.directive.js work.
