### ISSUE TITLE
createCredentials() is deprecated, use tls.createSecureContext instead

### ISSUE THREAD

**Issue by GregTurner** [BCDevExchange/BCDevExchange-app#65]
One of our packages has a deprecated API call

**Comment by GregTurner** [comment]
Waiting for NPM bump:

https://github.com/ciaranj/node-oauth/issues/238

**Comment by kelpisland** [comment]
This was an old issue from R1. It's currently serving as a test case for Waffle

**Comment by kelpisland** [comment]
Closing  - served it's purpose
