### ISSUE TITLE
link to 'Community Tools' on homepage hits 404

### ISSUE THREAD

**Issue by ivar** [BCDevExchange/BCDevExchange-app#73]
The URL used for the 'View in Github' button ( https://github.com/BCDevExchange/Community-Tools ) is 404 for public users. I can't find anything like 'community tools' repo under BCDevExchange so either the repo is private or there's a typo somewhere.

**Comment by h3devin** [comment]
Thanks for spotting that one.  We removed that repo and it's now removed from our list.
