### ISSUE TITLE
Installation of forever

### ISSUE THREAD

**Issue by msmackle** [BCDevExchange/BCDevExchange-app#76]
I just tried the build and installation process on both a clean 14.04 virtual and a 14.04 Ubuntu Cloud AMI, and in both cases the described process required an explicit npm install of forever in the section labelled "Installing or Upgrading NodeJS via N" or "Server Deployment". Adding the command

     sudo npm install -g forever

resulted in the rest of the page working as described.

**Comment by h3devin** [comment]
Thanks for catching that.  The README has been updated!
